name: Build VENTUS

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout LLVM
      uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        registry-url: 'https://registry.npmjs.org'

    - name: Install Ninja
      uses: llvm/actions/install-ninja@main

    - name: Start building VENTUS
      run: |
        # CMake and  Ninja are needed
        cmake --version
        ninja --version
        
